# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/m154',
                'doc_host': 'https://tesfaasmara.github.io',
                'git_url': 'https://github.com/tesfaasmara/m154',
                'lib_path': 'm154'},
  'syms': {}}